### ISSUE TITLE
release2.0.0和pre release2.1.0经测试，发现routes列表报错

### ISSUE THREAD

**Issue by parkerisme** [raoxiaoyan/kongx#7]
kong2.1.4下
查看路由列表时，10次有1次大概会成功显示列表。9次不成功，一直转圈。查看浏览器控制台，报错如下：
Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
chunk-705d6594.ef883edb.js:1 Kong version : 2.1.4 ,Entity : Routes
chunk-705d6594.ef883edb.js:1 Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
    at chunk-705d6594.ef883edb.js:1
    at Array.forEach (<anonymous>)
    at chunk-705d6594.ef883edb.js:1
    at Array.forEach (<anonymous>)
    at chunk-705d6594.ef883edb.js:1

找到问题了。如果路由下的服务为空，就报错了。可否给代码加上容错能力呢？

**Comment by raoxiaoyan** [comment]
> 

路由必须依附在service下，否则没有存在的意义。
